ALTER TABLE "Restaurant"
  ADD COLUMN "logoUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "coverImageUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "brandColor" TEXT NOT NULL DEFAULT '#17372b';

ALTER TABLE "MenuItem"
  ADD COLUMN "imageUrl" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "prepMinutes" INTEGER NOT NULL DEFAULT 15;

ALTER TABLE "Order" ADD COLUMN "estimatedReadyAt" TIMESTAMP(3);
