import { useEffect, useMemo, useState } from "react";
import { api } from "./api";
import type { Category } from "./types";
import { AlertSoundPicker, type AlertSoundId } from "./AlertSounds";

type TicketItem={id:string;quantity:number;notes?:string;orderItem:{name:string}};
type Ticket={id:string;status:string;priority:number;createdAt:string;station:{id:string;name:string;color:string};order:{displayId:string;tableLabel:string;createdAt:string;status:string};items:TicketItem[]};
type Station={id:string;name:string;code:string;color:string;sortOrder:number;isActive:boolean;categories:{category:{id:string;name:string}}[]};
const stages=["QUEUED","ACKNOWLEDGED","PREPARING","READY"] as const;
const nextStatus:Record<string,string>={QUEUED:"ACKNOWLEDGED",ACKNOWLEDGED:"PREPARING",PREPARING:"READY",READY:"COMPLETED"};

export function KdsPage({token,canManage,canPrepare,onMessage,orderSound,orderSoundBlocked,onOrderSoundChange,onTestOrderSound,onOrderCountChange}:{token:string;canManage:boolean;canPrepare:boolean;onMessage:(message:string,error?:boolean)=>void;orderSound:AlertSoundId;orderSoundBlocked:boolean;onOrderSoundChange:(sound:AlertSoundId)=>void;onTestOrderSound:()=>void;onOrderCountChange:(count:number)=>void}){
  const[stations,setStations]=useState<Station[]>([]),[tickets,setTickets]=useState<Ticket[]>([]),[categories,setCategories]=useState<Category[]>([]);
  const[selected,setSelected]=useState("all"),[setupOpen,setSetupOpen]=useState(false),[busy,setBusy]=useState("");
  const[name,setName]=useState(""),[code,setCode]=useState(""),[categoryIds,setCategoryIds]=useState<string[]>([]);
  const loadSetup=async()=>{const[a,c]=await Promise.all([api<Station[]>("/api/admin/kds/stations",token),api<Category[]>("/api/admin/menu",token)]);setStations(a);setCategories(c)};
  const loadTickets=async()=>setTickets(await api<Ticket[]>(`/api/admin/kds/tickets${selected==="all"?"":`?stationId=${encodeURIComponent(selected)}`}`,token));
  useEffect(()=>{void loadSetup().catch(error=>onMessage(error instanceof Error?error.message:"Could not load kitchen stations",true))},[token]);
  useEffect(()=>{void loadTickets().catch(error=>onMessage(error instanceof Error?error.message:"Could not load kitchen tickets",true));const timer=window.setInterval(()=>void loadTickets().catch(()=>undefined),4000);return()=>window.clearInterval(timer)},[token,selected]);
  useEffect(()=>{const sync=()=>void Promise.all([loadSetup(),loadTickets()]).catch(()=>undefined);window.addEventListener("white_label:restaurant-sync",sync);return()=>window.removeEventListener("white_label:restaurant-sync",sync)},[token,selected]);
  const counts=useMemo(()=>Object.fromEntries(stages.map(stage=>[stage,tickets.filter(ticket=>ticket.status===stage).length])),[tickets]);
  const orderCount=useMemo(()=>new Set(tickets.map(ticket=>ticket.order.displayId)).size,[tickets]);
  useEffect(()=>onOrderCountChange(orderCount),[onOrderCountChange,orderCount]);
  const execute=async(key:string,action:()=>Promise<unknown>)=>{if(busy)return;setBusy(key);try{await action();await Promise.all([loadSetup(),loadTickets()]);onMessage("Kitchen board updated")}catch(error){onMessage(error instanceof Error?error.message:"Kitchen update failed",true)}finally{setBusy("")}};
  return <div className="station-kds">
    <section className="operations-hero kds-hero"><div><p className="eyebrow">Station-based KDS</p><h2>Live production board</h2><p>Route each menu category to its production station and complete tickets independently.</p></div><div className="operations-hero-controls"><AlertSoundPicker label="New order alert" value={orderSound} blocked={orderSoundBlocked} onChange={onOrderSoundChange} onTest={onTestOrderSound}/><div className="operations-kpis"><span><b>{orderCount}</b> open orders</span><span><b>{tickets.length}</b> open tickets</span><span><b>{counts.READY||0}</b> ready</span></div></div></section>
    {!canPrepare&&<div className="notice read-only-notice" role="note"><b>Read-only kitchen board</b><p>Your role can monitor tickets but cannot move them through preparation stages.</p></div>}
    <div className="kds-station-bar"><div className="operations-tabs"><button className={selected==="all"?"active":""} onClick={()=>setSelected("all")}>All stations</button>{stations.filter(station=>station.isActive).map(station=><button className={selected===station.id?"active":""} style={{"--station-color":station.color} as React.CSSProperties} key={station.id} onClick={()=>setSelected(station.id)}>{station.name}</button>)}</div>{canManage&&<button className="secondary-action" onClick={()=>setSetupOpen(value=>!value)}>{setupOpen?"Close setup":"Manage stations"}</button>}</div>
    {setupOpen&&<section className="operations-card station-setup"><header><h3>Add production station</h3><span>Assign categories once; new tickets route automatically.</span></header><form onSubmit={event=>{event.preventDefault();void execute("station",async()=>{await api("/api/admin/kds/stations",token,{method:"POST",body:JSON.stringify({name,code,categoryIds,sortOrder:stations.length+1})});setName("");setCode("");setCategoryIds([])})}}><div className="form-row"><label><span>Station name</span><input required minLength={2} value={name} onChange={e=>setName(e.target.value)}/></label><label><span>Code</span><input required minLength={2} maxLength={16} value={code} onChange={e=>setCode(e.target.value.toUpperCase())}/></label></div><fieldset><legend>Menu categories</legend><div className="check-grid">{categories.map(category=><label key={category.id}><input type="checkbox" checked={categoryIds.includes(category.id)} onChange={event=>setCategoryIds(current=>event.target.checked?[...current,category.id]:current.filter(id=>id!==category.id))}/><span>{category.name}</span></label>)}</div></fieldset><button disabled={Boolean(busy)}>{busy==="station"?"Adding…":"Add station"}</button></form></section>}
    <div className="station-kds-grid">{stages.map(stage=><section className={`station-column station-${stage.toLowerCase()}`} key={stage}><header><span>{stage.replace("_"," ")}</span><b>{counts[stage]||0}</b></header>{tickets.filter(ticket=>ticket.status===stage).map(ticket=><article className="station-ticket" style={{"--station-color":ticket.station.color} as React.CSSProperties} key={ticket.id}><div className="station-ticket-head"><div><b>{ticket.order.tableLabel}</b><small>{ticket.order.displayId}</small></div><span>{ticket.station.name}</span></div><time>{Math.max(0,Math.floor((Date.now()-new Date(ticket.createdAt).getTime())/60000))} min</time><ul>{ticket.items.map(item=><li key={item.id}><strong>{item.quantity}×</strong><span>{item.orderItem.name}{item.notes&&<small>{item.notes}</small>}</span></li>)}</ul>{canPrepare&&<button disabled={Boolean(busy)} onClick={()=>void execute(ticket.id,()=>api(`/api/admin/kds/tickets/${ticket.id}/status`,token,{method:"PATCH",body:JSON.stringify({status:nextStatus[ticket.status]})}))}>{stage==="QUEUED"?"Acknowledge":stage==="ACKNOWLEDGED"?"Start cooking":stage==="PREPARING"?"Mark ready":"Complete"}</button>}</article>)}</section>)}</div>
  </div>;
}
