import { useState, type FormEvent } from "react";
import type { SupportTicket } from "./types";

const PRODUCT_NAME = import.meta.env.VITE_PRODUCT_NAME || "Platform";

export function SupportTicketsCard({ tickets, onCreate }: { tickets: SupportTicket[]; onCreate: (data: { subject: string; category: string; priority: string; message: string }) => Promise<boolean> }) {
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); const ok = await onCreate({ subject: String(data.get("subject")).trim(), category: String(data.get("category")), priority: String(data.get("priority")), message: String(data.get("message")).trim() }); setBusy(false); if (ok) form.reset(); }
  return <section className="support-ticket-card"><div><p className="eyebrow">{PRODUCT_NAME.toUpperCase()} SUPPORT</p><h2>Need help?</h2><p>Create a ticket and keep its status with your restaurant account.</p></div><form onSubmit={submit}><label>Subject<input name="subject" minLength={4} maxLength={120} required placeholder="What do you need help with?" /></label><div className="support-ticket-fields"><label>Category<select name="category" defaultValue="TECHNICAL"><option value="TECHNICAL">Technical</option><option value="PAYMENTS">Payments</option><option value="ACCOUNT">Account</option><option value="BILLING">Billing</option><option value="OTHER">Other</option></select></label><label>Priority<select name="priority" defaultValue="NORMAL"><option value="NORMAL">Normal</option><option value="HIGH">High</option><option value="URGENT">Urgent</option></select></label></div><label>Details<textarea name="message" minLength={10} maxLength={2000} rows={4} required placeholder="Describe the issue and what you expected to happen." /></label><button disabled={busy}>{busy ? "Creating…" : "Create support ticket"}</button></form>{tickets.length > 0 && <div className="support-ticket-list"><h3>Recent tickets</h3>{tickets.slice(0,3).map(ticket => <article key={ticket.id}><div><b>{ticket.subject}</b><small>{ticket.category.toLowerCase()} · {new Date(ticket.createdAt).toLocaleDateString()}</small></div><span className={`ticket-status ${ticket.status.toLowerCase()}`}>{ticket.status}</span></article>)}</div>}</section>;
}
